name: Pull request workflow

on:
  pull_request:
   
jobs:
  lint:
   name: Analyze code and lint
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.1
      with:
        version: 7

    - name: Install Node JS
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'pnpm'

    - name: Install dependencies (Client)
      run: pnpm install --dir client

    - name: Start Lint (Client)
      run: pnpm run --dir client lint
    
    - name: Install dependencies (Server)
      run: pnpm install --dir server

    - name: Start Lint (server)
      run: pnpm run --dir server lint
